package com.locallens.app.data.db

import android.content.Context
import io.objectbox.BoxStore
import io.objectbox.android.Admin
// MyObjectBox is generated by the ObjectBox annotation processor at build time
import com.locallens.app.data.db.entities.MyObjectBox

object AppDatabase {
    private var boxStore: BoxStore? = null

    fun init(context: Context): BoxStore {
        if (boxStore == null) {
            boxStore = MyObjectBox.builder()
                .androidContext(context.applicationContext)
                .build()
        }
        return boxStore!!
    }

    fun get(): BoxStore {
        return boxStore ?: throw IllegalStateException("AppDatabase not initialized. Call init() first.")
    }

    fun close() {
        boxStore?.close()
        boxStore = null
    }
}
